<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>1481505a-56a5-40d1-85bd-dfbd0bb180fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.c-search__button.c-button--primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b9532b58-8ffc-42ea-affe-89b0c35863e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>89c233c4-bc80-448f-ade9-e7281722bff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-search__button c-button--primary</value>
      <webElementGuid>63e1ce49-ed03-4c07-b153-90fb4d913212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        Search
      </value>
      <webElementGuid>435040e5-2d09-4036-a2c5-2a572537c3ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vue-flight-overview-table&quot;)/div[1]/div[@class=&quot;c-search__container container&quot;]/div[@class=&quot;c-table-search&quot;]/div[@class=&quot;c-table-search__search-component&quot;]/form[@class=&quot;inner-form&quot;]/div[@class=&quot;input-field second-wrap&quot;]/button[@class=&quot;c-search__button c-button--primary&quot;]</value>
      <webElementGuid>3111dd01-f735-4318-a3c9-e8101628ff24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>60626071-7f68-4928-a3a9-a283c437f570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vue-flight-overview-table']/div/div/div/div[2]/form/div[2]/button</value>
      <webElementGuid>e4328eb2-0eed-4a10-8cbd-01c80e1a7441</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='to'])[1]/preceding::button[1]</value>
      <webElementGuid>92e0a967-1a8c-40e8-9c12-199301ef1f13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Istanbul'])[1]/preceding::button[1]</value>
      <webElementGuid>060d9e7c-64f7-486d-b0b9-d426c9cdbf64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Search']/parent::*</value>
      <webElementGuid>cf0c1113-1fdb-4f25-aa8a-a5bee033e370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/button</value>
      <webElementGuid>52e63f85-2ddb-4d90-9e7e-817183730e9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '
        Search
      ' or . = '
        Search
      ')]</value>
      <webElementGuid>a3349556-5ff6-4e86-8a65-8754fcc0e1f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
