<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Destinations_search-query</name>
   <tag></tag>
   <elementGuidId>50f007bd-8bdc-4781-bb46-545becd66f0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='search-query'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.input-field.first-wrap.c-field-group.c-field-group--big > input[name=&quot;search-query&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f68d695e-18e5-4e85-85c2-eada1dbed604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Destination or flight number</value>
      <webElementGuid>3b54cbd5-03e4-498a-9c62-ed7bc253b641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search-query</value>
      <webElementGuid>b728e27b-9cd0-4159-bbe3-b38e221b125b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2398dab4-c7e0-4650-b979-2f6b465319c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7139cb9f-792c-441e-8e21-8cf085a4c157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control c-field c-search-field focus-visible</value>
      <webElementGuid>bd8a5a97-d1d7-4f8f-9d4c-fa44cc62c692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vue-flight-overview-table&quot;)/div[1]/div[@class=&quot;c-search__container container&quot;]/div[@class=&quot;c-table-search&quot;]/div[@class=&quot;c-table-search__search-component&quot;]/form[@class=&quot;inner-form&quot;]/div[@class=&quot;input-field first-wrap c-field-group c-field-group--big&quot;]/input[@class=&quot;form-control c-field c-search-field focus-visible&quot;]</value>
      <webElementGuid>9431c23b-9162-426a-b6b0-e1930907188d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='search-query'])[2]</value>
      <webElementGuid>994c0f7c-5794-496f-b2d1-7a5696dea493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vue-flight-overview-table']/div/div/div/div[2]/form/div/input</value>
      <webElementGuid>fe99f621-0dd2-477a-91fb-5c2168dc0980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input</value>
      <webElementGuid>6d869628-302c-4ba5-bc0c-5080327fae70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Destination or flight number' and @name = 'search-query' and @type = 'text']</value>
      <webElementGuid>9e467c17-6d9e-406f-bf85-2fdc5f4eccea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
