<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Flights</name>
   <tag></tag>
   <elementGuidId>d2ec6f87-a460-4ffe-a2d2-c08683d72c0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='dropdownId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dropdownId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>29257b9a-aabb-4832-8766-fe600dd79bbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link dropdown-toggle </value>
      <webElementGuid>5c3d36c9-ed51-4368-b8af-94eb52d0d9d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dropdownId</value>
      <webElementGuid>aeebe209-1b00-47ad-a5c3-e0994bba9753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en/passengers/flights</value>
      <webElementGuid>ae517d01-0e78-4bf5-be71-ce5ed472cc0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f5f54277-971b-42ed-83d6-9b9d3be91969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Flights
                        </value>
      <webElementGuid>a2b19eba-d6eb-497e-ac19-ee524ea65a9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vertical-1-measure&quot;)/li[@class=&quot;c-nav-primary-bar__mi nav-item nav-item-parent position-relative d-flex top-item&quot;]/a[@id=&quot;dropdownId&quot;]</value>
      <webElementGuid>ed8aa691-34d9-4833-9ead-7573d43acb8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='dropdownId']</value>
      <webElementGuid>2477ed1f-5d16-4f9d-b72b-d87bbc52db17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='vertical-1-measure']/li[2]/a</value>
      <webElementGuid>c42f9199-a90e-43cc-8426-10d3a5676c24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Flights')]</value>
      <webElementGuid>7e0f24f3-52d9-458f-923f-bab35c2e32b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up'])[3]/following::a[1]</value>
      <webElementGuid>8878847c-2ab9-4d30-9874-b0d11b81bac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[3]/following::a[2]</value>
      <webElementGuid>58c8495f-7393-47eb-ad63-2c57597977bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Departures'])[2]/preceding::a[1]</value>
      <webElementGuid>a8e7ea48-14fb-45eb-a531-c8cd0b7318a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Arrivals'])[2]/preceding::a[2]</value>
      <webElementGuid>4f9a25f3-514a-4513-926f-4b2a8109bba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/en/passengers/flights')])[4]</value>
      <webElementGuid>ff0896fc-b2bf-4c53-a509-433e7303d447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li[2]/a</value>
      <webElementGuid>ebdfc53b-7fe9-4830-8a6d-9bd43e97ae64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'dropdownId' and @href = '/en/passengers/flights' and (text() = '
                            Flights
                        ' or . = '
                            Flights
                        ')]</value>
      <webElementGuid>9b517beb-cbdd-40bb-9c6d-708eb23e238d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
