<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>775cc3be-d1f6-466c-b1ee-64c6da2f1650</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.c-search__button.c-button--primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c595a763-4a66-4671-a039-fca541460120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>8061336e-0235-457e-8c5a-1805c23890f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-search__button c-button--primary</value>
      <webElementGuid>d276c363-5dae-4b17-8dee-e451778588b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        Search
      </value>
      <webElementGuid>4488c5b6-3963-4cc3-bb89-102d794b5e1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vue-flight-overview-table&quot;)/div[1]/div[@class=&quot;c-search__container container&quot;]/div[@class=&quot;c-table-search&quot;]/div[@class=&quot;c-table-search__search-component&quot;]/form[@class=&quot;inner-form&quot;]/div[@class=&quot;input-field second-wrap&quot;]/button[@class=&quot;c-search__button c-button--primary&quot;]</value>
      <webElementGuid>b0a95db3-d4df-4fa8-ba0e-a4847c038500</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>2bc6ae18-b98f-4736-8e9a-5fc115402747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vue-flight-overview-table']/div/div/div/div[2]/form/div[2]/button</value>
      <webElementGuid>53318fed-559e-4a6f-b098-585c613e1cb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='from'])[1]/preceding::button[1]</value>
      <webElementGuid>2c5c3e10-646b-49af-8626-a83d7363ed8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Istanbul'])[1]/preceding::button[1]</value>
      <webElementGuid>76096f24-8ec7-49d8-9b6b-12a81339ce2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Search']/parent::*</value>
      <webElementGuid>403ae295-be56-47b6-be5b-5fafaa3a0853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/button</value>
      <webElementGuid>2f16c930-6722-4015-a49f-da8e27cf9a88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '
        Search
      ' or . = '
        Search
      ')]</value>
      <webElementGuid>1b76f553-0517-4e0c-bae4-742d010f4e5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
