<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Destinations_search-query</name>
   <tag></tag>
   <elementGuidId>88471af1-9494-4bf6-97cc-b4737cc32f45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='search-query'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.input-field.first-wrap.c-field-group.c-field-group--big > input[name=&quot;search-query&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a705bc8f-0ef7-4901-ba46-49ef415bf912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Origin or flight number</value>
      <webElementGuid>bf785417-874a-4f6b-899d-40bc824e38ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search-query</value>
      <webElementGuid>23f43836-5056-4024-9b0d-54b86424a8be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>12754c00-956c-44ee-9904-760bfa927963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>dfca1710-36e5-4509-912e-bba300412954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control c-field c-search-field focus-visible</value>
      <webElementGuid>2a467f18-765e-4ec7-b7d6-196a8a3f93a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vue-flight-overview-table&quot;)/div[1]/div[@class=&quot;c-search__container container&quot;]/div[@class=&quot;c-table-search&quot;]/div[@class=&quot;c-table-search__search-component&quot;]/form[@class=&quot;inner-form&quot;]/div[@class=&quot;input-field first-wrap c-field-group c-field-group--big&quot;]/input[@class=&quot;form-control c-field c-search-field focus-visible&quot;]</value>
      <webElementGuid>e5273618-3eb9-4806-9d88-a4ccd5c8f6e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='search-query'])[2]</value>
      <webElementGuid>d9311bf7-108b-493f-813a-03333741a236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vue-flight-overview-table']/div/div/div/div[2]/form/div/input</value>
      <webElementGuid>0fb4b347-297c-43bb-b9bc-84ba32956cde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input</value>
      <webElementGuid>eb1fdc5e-51af-432a-8e3f-7148be1b14db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Origin or flight number' and @name = 'search-query' and @type = 'text']</value>
      <webElementGuid>15c8d8be-6253-45ab-af2e-963aa4e0254b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
