<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Flights</name>
   <tag></tag>
   <elementGuidId>3b2179d4-2911-48ae-835e-f64ddce26b27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='dropdownId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dropdownId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5c25b9d2-32c4-4958-a6b9-651bb7c44cd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link dropdown-toggle </value>
      <webElementGuid>61eb6d4b-ad95-4549-83ab-d2ae348cd98a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dropdownId</value>
      <webElementGuid>6638b710-615d-4035-b6ef-31ef30e08bc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en/passengers/flights</value>
      <webElementGuid>0b276628-8f17-4b4d-86ac-e706650b150d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a31bbdc8-dabc-4250-b336-6c8ccf80c877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Flights
                        </value>
      <webElementGuid>94e931af-380a-401a-989a-52538ede0e56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vertical-1-measure&quot;)/li[@class=&quot;c-nav-primary-bar__mi nav-item nav-item-parent position-relative d-flex top-item&quot;]/a[@id=&quot;dropdownId&quot;]</value>
      <webElementGuid>4615cf0a-1b7f-41e6-8246-fb7221bbaaed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='dropdownId']</value>
      <webElementGuid>8500a623-5d61-4a68-ac63-862d8395a060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='vertical-1-measure']/li[2]/a</value>
      <webElementGuid>190c6c06-91a6-47b6-b861-3460657c2b34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Flights')]</value>
      <webElementGuid>bd5005e1-27b9-4610-86d0-e878de732614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up'])[3]/following::a[1]</value>
      <webElementGuid>96c8d8b8-a8a3-4ec5-ac3e-34be111c51d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[3]/following::a[2]</value>
      <webElementGuid>d583b054-154a-4593-b684-8e00171b4f39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Departures'])[2]/preceding::a[1]</value>
      <webElementGuid>c14e5a91-e01a-4347-a0eb-64929f6bd6cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Arrivals'])[2]/preceding::a[2]</value>
      <webElementGuid>a58f229b-accb-4cad-85b1-b48e6c885804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/en/passengers/flights')])[4]</value>
      <webElementGuid>3d2610f4-6997-45bc-ab59-d97ea6db4316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li[2]/a</value>
      <webElementGuid>29076abc-17a7-4854-be0e-94982e1b6bf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'dropdownId' and @href = '/en/passengers/flights' and (text() = '
                            Flights
                        ' or . = '
                            Flights
                        ')]</value>
      <webElementGuid>ac4fee23-3cbe-4d1b-842c-404cab4c198d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
